// Code generated by gowsdl DO NOT EDIT.

package creativereview

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type ApiVersionError_Reason string

const (
	ApiVersionError_ReasonUPDATE_TO_NEWER_VERSION ApiVersionError_Reason = "UPDATE_TO_NEWER_VERSION"

	ApiVersionError_ReasonUNKNOWN ApiVersionError_Reason = "UNKNOWN"
)

type AuthenticationError_Reason string

const (
	AuthenticationError_ReasonAMBIGUOUS_SOAP_REQUEST_HEADER AuthenticationError_Reason = "AMBIGUOUS_SOAP_REQUEST_HEADER"

	AuthenticationError_ReasonINVALID_EMAIL AuthenticationError_Reason = "INVALID_EMAIL"

	AuthenticationError_ReasonAUTHENTICATION_FAILED AuthenticationError_Reason = "AUTHENTICATION_FAILED"

	AuthenticationError_ReasonINVALID_OAUTH_SIGNATURE AuthenticationError_Reason = "INVALID_OAUTH_SIGNATURE"

	AuthenticationError_ReasonINVALID_SERVICE AuthenticationError_Reason = "INVALID_SERVICE"

	AuthenticationError_ReasonMISSING_SOAP_REQUEST_HEADER AuthenticationError_Reason = "MISSING_SOAP_REQUEST_HEADER"

	AuthenticationError_ReasonMISSING_AUTHENTICATION_HTTP_HEADER AuthenticationError_Reason = "MISSING_AUTHENTICATION_HTTP_HEADER"

	AuthenticationError_ReasonMISSING_AUTHENTICATION AuthenticationError_Reason = "MISSING_AUTHENTICATION"

	AuthenticationError_ReasonNETWORK_API_ACCESS_DISABLED AuthenticationError_Reason = "NETWORK_API_ACCESS_DISABLED"

	AuthenticationError_ReasonNO_NETWORKS_TO_ACCESS AuthenticationError_Reason = "NO_NETWORKS_TO_ACCESS"

	AuthenticationError_ReasonNETWORK_NOT_FOUND AuthenticationError_Reason = "NETWORK_NOT_FOUND"

	AuthenticationError_ReasonNETWORK_CODE_REQUIRED AuthenticationError_Reason = "NETWORK_CODE_REQUIRED"

	AuthenticationError_ReasonCONNECTION_ERROR AuthenticationError_Reason = "CONNECTION_ERROR"

	AuthenticationError_ReasonGOOGLE_ACCOUNT_ALREADY_ASSOCIATED_WITH_NETWORK AuthenticationError_Reason = "GOOGLE_ACCOUNT_ALREADY_ASSOCIATED_WITH_NETWORK"

	AuthenticationError_ReasonUNDER_INVESTIGATION AuthenticationError_Reason = "UNDER_INVESTIGATION"

	AuthenticationError_ReasonUNKNOWN AuthenticationError_Reason = "UNKNOWN"
)

type CollectionSizeError_Reason string

const (
	CollectionSizeError_ReasonTOO_LARGE CollectionSizeError_Reason = "TOO_LARGE"

	CollectionSizeError_ReasonUNKNOWN CollectionSizeError_Reason = "UNKNOWN"
)

type CommonError_Reason string

const (
	CommonError_ReasonNOT_FOUND CommonError_Reason = "NOT_FOUND"

	CommonError_ReasonALREADY_EXISTS CommonError_Reason = "ALREADY_EXISTS"

	CommonError_ReasonNOT_APPLICABLE CommonError_Reason = "NOT_APPLICABLE"

	CommonError_ReasonDUPLICATE_OBJECT CommonError_Reason = "DUPLICATE_OBJECT"

	CommonError_ReasonCANNOT_UPDATE CommonError_Reason = "CANNOT_UPDATE"

	CommonError_ReasonUNSUPPORTED_OPERATION CommonError_Reason = "UNSUPPORTED_OPERATION"

	CommonError_ReasonCONCURRENT_MODIFICATION CommonError_Reason = "CONCURRENT_MODIFICATION"

	CommonError_ReasonUNKNOWN CommonError_Reason = "UNKNOWN"
)

type FeatureError_Reason string

const (
	FeatureError_ReasonMISSING_FEATURE FeatureError_Reason = "MISSING_FEATURE"

	FeatureError_ReasonUNKNOWN FeatureError_Reason = "UNKNOWN"
)

type InternalApiError_Reason string

const (
	InternalApiError_ReasonUNEXPECTED_INTERNAL_API_ERROR InternalApiError_Reason = "UNEXPECTED_INTERNAL_API_ERROR"

	InternalApiError_ReasonTRANSIENT_ERROR InternalApiError_Reason = "TRANSIENT_ERROR"

	InternalApiError_ReasonUNKNOWN InternalApiError_Reason = "UNKNOWN"

	InternalApiError_ReasonDOWNTIME InternalApiError_Reason = "DOWNTIME"

	InternalApiError_ReasonERROR_GENERATING_RESPONSE InternalApiError_Reason = "ERROR_GENERATING_RESPONSE"
)

type NotNullError_Reason string

const (
	NotNullError_ReasonARG1_NULL NotNullError_Reason = "ARG1_NULL"

	NotNullError_ReasonARG2_NULL NotNullError_Reason = "ARG2_NULL"

	NotNullError_ReasonARG3_NULL NotNullError_Reason = "ARG3_NULL"

	NotNullError_ReasonNULL NotNullError_Reason = "NULL"

	NotNullError_ReasonUNKNOWN NotNullError_Reason = "UNKNOWN"
)

type ParseError_Reason string

const (
	ParseError_ReasonUNPARSABLE ParseError_Reason = "UNPARSABLE"

	ParseError_ReasonUNKNOWN ParseError_Reason = "UNKNOWN"
)

type PermissionError_Reason string

const (
	PermissionError_ReasonPERMISSION_DENIED PermissionError_Reason = "PERMISSION_DENIED"

	PermissionError_ReasonUNKNOWN PermissionError_Reason = "UNKNOWN"
)

type PublisherQueryLanguageContextError_Reason string

const (
	PublisherQueryLanguageContextError_ReasonUNEXECUTABLE PublisherQueryLanguageContextError_Reason = "UNEXECUTABLE"

	PublisherQueryLanguageContextError_ReasonUNKNOWN PublisherQueryLanguageContextError_Reason = "UNKNOWN"
)

type PublisherQueryLanguageSyntaxError_Reason string

const (
	PublisherQueryLanguageSyntaxError_ReasonUNPARSABLE PublisherQueryLanguageSyntaxError_Reason = "UNPARSABLE"

	PublisherQueryLanguageSyntaxError_ReasonUNKNOWN PublisherQueryLanguageSyntaxError_Reason = "UNKNOWN"
)

type QuotaError_Reason string

const (
	QuotaError_ReasonEXCEEDED_QUOTA QuotaError_Reason = "EXCEEDED_QUOTA"

	QuotaError_ReasonUNKNOWN QuotaError_Reason = "UNKNOWN"

	QuotaError_ReasonREPORT_JOB_LIMIT QuotaError_Reason = "REPORT_JOB_LIMIT"

	QuotaError_ReasonSEGMENT_POPULATION_LIMIT QuotaError_Reason = "SEGMENT_POPULATION_LIMIT"
)

type RequiredCollectionError_Reason string

const (
	RequiredCollectionError_ReasonREQUIRED RequiredCollectionError_Reason = "REQUIRED"

	RequiredCollectionError_ReasonTOO_LARGE RequiredCollectionError_Reason = "TOO_LARGE"

	RequiredCollectionError_ReasonTOO_SMALL RequiredCollectionError_Reason = "TOO_SMALL"

	RequiredCollectionError_ReasonUNKNOWN RequiredCollectionError_Reason = "UNKNOWN"
)

type RequiredError_Reason string

const (
	RequiredError_ReasonREQUIRED RequiredError_Reason = "REQUIRED"
)

type ServerError_Reason string

const (
	ServerError_ReasonSERVER_ERROR ServerError_Reason = "SERVER_ERROR"

	ServerError_ReasonSERVER_BUSY ServerError_Reason = "SERVER_BUSY"

	ServerError_ReasonUNKNOWN ServerError_Reason = "UNKNOWN"
)

type StatementError_Reason string

const (
	StatementError_ReasonVARIABLE_NOT_BOUND_TO_VALUE StatementError_Reason = "VARIABLE_NOT_BOUND_TO_VALUE"

	StatementError_ReasonUNKNOWN StatementError_Reason = "UNKNOWN"
)

type StringFormatError_Reason string

const (
	StringFormatError_ReasonUNKNOWN StringFormatError_Reason = "UNKNOWN"

	StringFormatError_ReasonILLEGAL_CHARS StringFormatError_Reason = "ILLEGAL_CHARS"

	StringFormatError_ReasonINVALID_FORMAT StringFormatError_Reason = "INVALID_FORMAT"
)

type StringLengthError_Reason string

const (
	StringLengthError_ReasonTOO_LONG StringLengthError_Reason = "TOO_LONG"

	StringLengthError_ReasonTOO_SHORT StringLengthError_Reason = "TOO_SHORT"

	StringLengthError_ReasonUNKNOWN StringLengthError_Reason = "UNKNOWN"
)

type GetCreativeReviewsByStatement struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 getCreativeReviewsByStatement"`

	Statement *Statement `xml:"statement,omitempty" json:"statement,omitempty"`
}

type GetCreativeReviewsByStatementResponse struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 getCreativeReviewsByStatementResponse"`

	Rval *CreativeReviewPage `xml:"rval,omitempty" json:"rval,omitempty"`
}

type ApiExceptionFault ApiException

type PerformCreativeReviewAction struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 performCreativeReviewAction"`

	CreativeReviewAction *CreativeReviewAction `xml:"creativeReviewAction,omitempty" json:"creativeReviewAction,omitempty"`

	FilterStatement *Statement `xml:"filterStatement,omitempty" json:"filterStatement,omitempty"`
}

type PerformCreativeReviewActionResponse struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 performCreativeReviewActionResponse"`

	Rval *UpdateResult `xml:"rval,omitempty" json:"rval,omitempty"`
}

type RequestHeader SoapRequestHeader

type ResponseHeader SoapResponseHeader

type ObjectValue struct {
	*_Value
}

type ApiError struct {
	FieldPath string `xml:"fieldPath,omitempty" json:"fieldPath,omitempty"`

	FieldPathElements []*FieldPathElement `xml:"fieldPathElements,omitempty" json:"fieldPathElements,omitempty"`

	Trigger string `xml:"trigger,omitempty" json:"trigger,omitempty"`

	ErrorString string `xml:"errorString,omitempty" json:"errorString,omitempty"`
}

type ApiException struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 ApiExceptionFault"`

	*ApplicationException

	Errors []*ApiError `xml:"errors,omitempty" json:"errors,omitempty"`
}

type ApiVersionError struct {
	*ApiError

	Reason *ApiVersionError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type ApplicationException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type ApproveCreativeReviews struct {
	*CreativeReviewAction
}

type ArchiveCreativeReviews struct {
	*CreativeReviewAction
}

type AuthenticationError struct {
	*ApiError

	Reason *AuthenticationError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type BooleanValue struct {
	*_Value

	Value bool `xml:"value,omitempty" json:"value,omitempty"`
}

type CollectionSizeError struct {
	*ApiError

	Reason *CollectionSizeError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type CommonError struct {
	*ApiError

	Reason *CommonError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type CreativeReviewAction struct {
}

type CreativeReview struct {

	//
	// This attribute is read-only.
	//
	Id string `xml:"id,omitempty" json:"id,omitempty"`

	//
	// This attribute is read-only.
	//
	ReviewableUrl string `xml:"reviewableUrl,omitempty" json:"reviewableUrl,omitempty"`

	//
	// This attribute is read-only.
	//
	Impressions int64 `xml:"impressions,omitempty" json:"impressions,omitempty"`
}

type CreativeReviewPage struct {
	TotalResultSetSize int32 `xml:"totalResultSetSize,omitempty" json:"totalResultSetSize,omitempty"`

	StartIndex int32 `xml:"startIndex,omitempty" json:"startIndex,omitempty"`

	Results []*CreativeReview `xml:"results,omitempty" json:"results,omitempty"`
}

type Date struct {
	Year int32 `xml:"year,omitempty" json:"year,omitempty"`

	Month int32 `xml:"month,omitempty" json:"month,omitempty"`

	Day int32 `xml:"day,omitempty" json:"day,omitempty"`
}

type DateTime struct {
	Date soap.XSDDate `xml:"date,omitempty" json:"date,omitempty"`

	Hour int32 `xml:"hour,omitempty" json:"hour,omitempty"`

	Minute int32 `xml:"minute,omitempty" json:"minute,omitempty"`

	Second int32 `xml:"second,omitempty" json:"second,omitempty"`

	TimeZoneId string `xml:"timeZoneId,omitempty" json:"timeZoneId,omitempty"`
}

type DateTimeValue struct {
	*_Value

	Value soap.XSDDateTime `xml:"value,omitempty" json:"value,omitempty"`
}

type DateValue struct {
	*_Value

	Value soap.XSDDate `xml:"value,omitempty" json:"value,omitempty"`
}

type DisapproveCreativeReviews struct {
	*CreativeReviewAction
}

type FeatureError struct {
	*ApiError

	Reason *FeatureError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type FieldPathElement struct {
	Field string `xml:"field,omitempty" json:"field,omitempty"`

	Index int32 `xml:"index,omitempty" json:"index,omitempty"`
}

type InternalApiError struct {
	*ApiError

	Reason *InternalApiError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type NotNullError struct {
	*ApiError

	Reason *NotNullError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type NumberValue struct {
	*_Value

	Value string `xml:"value,omitempty" json:"value,omitempty"`
}

type ParseError struct {
	*ApiError

	Reason *ParseError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type PermissionError struct {
	*ApiError

	Reason *PermissionError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type PublisherQueryLanguageContextError struct {
	*ApiError

	Reason *PublisherQueryLanguageContextError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type PublisherQueryLanguageSyntaxError struct {
	*ApiError

	Reason *PublisherQueryLanguageSyntaxError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type QuotaError struct {
	*ApiError

	Reason *QuotaError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type RequiredCollectionError struct {
	*ApiError

	Reason *RequiredCollectionError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type RequiredError struct {
	*ApiError

	Reason *RequiredError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type ServerError struct {
	*ApiError

	Reason *ServerError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type SetValue struct {
	*_Value

	Values []*_Value `xml:"values,omitempty" json:"values,omitempty"`
}

type SoapRequestHeader struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 RequestHeader"`

	NetworkCode string `xml:"networkCode,omitempty" json:"networkCode,omitempty"`

	ApplicationName string `xml:"applicationName,omitempty" json:"applicationName,omitempty"`
}

type SoapResponseHeader struct {
	XMLName xml.Name `xml:"https://www.google.com/apis/ads/publisher/v202311 ResponseHeader"`

	RequestId string `xml:"requestId,omitempty" json:"requestId,omitempty"`

	ResponseTime int64 `xml:"responseTime,omitempty" json:"responseTime,omitempty"`
}

type Statement struct {
	Query string `xml:"query,omitempty" json:"query,omitempty"`

	Values []*String_ValueMapEntry `xml:"values,omitempty" json:"values,omitempty"`
}

type StatementError struct {
	*ApiError

	Reason *StatementError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type StringFormatError struct {
	*ApiError

	Reason *StringFormatError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type StringLengthError struct {
	*ApiError

	Reason *StringLengthError_Reason `xml:"reason,omitempty" json:"reason,omitempty"`
}

type String_ValueMapEntry struct {
	Key string `xml:"key,omitempty" json:"key,omitempty"`

	Value *_Value `xml:"value,omitempty" json:"value,omitempty"`
}

type TextValue struct {
	*_Value

	Value string `xml:"value,omitempty" json:"value,omitempty"`
}

type UpdateResult struct {
	NumChanges int32 `xml:"numChanges,omitempty" json:"numChanges,omitempty"`
}

type _Value struct {
}

type CreativeReviewServiceInterface interface {

	// Error can be either of the following types:
	//
	//   - ApiException
	/*
	   Gets a {@link CreativeReviewPage} of {@link CreativeReview} objects that satisfy the given
	   {@link Statement#query}. This will allow you to review creatives that have displayed (or could
	   have displayed) on your pages or apps in the last 30 days. To ensure that you are always
	   reviewing the most important creatives first, the {@link CreativeReview} objects are ranked
	   according to the number of impressions that they've received.

	   <p>This feature is not yet openly available. Publishers will need to apply for access for this
	   feature through their account managers.
	*/
	GetCreativeReviewsByStatement(request *GetCreativeReviewsByStatement) (*GetCreativeReviewsByStatementResponse, error)

	GetCreativeReviewsByStatementContext(ctx context.Context, request *GetCreativeReviewsByStatement) (*GetCreativeReviewsByStatementResponse, error)

	// Error can be either of the following types:
	//
	//   - ApiException
	/*
	   Performs actions on {@link CreativeReview} objects that match the given {@link
	   Statement#query}. You can use actions to approve (allow) or disapprove (block) creatives, as
	   seen in the corresponding {@link CreativeReview} objects. You can also archive creatives to
	   allow you to retrieve new {@link CreativeReview} objects while previously retrieved {@link
	   CreativeReview} objects are in pending approval.
	*/
	PerformCreativeReviewAction(request *PerformCreativeReviewAction) (*PerformCreativeReviewActionResponse, error)

	PerformCreativeReviewActionContext(ctx context.Context, request *PerformCreativeReviewAction) (*PerformCreativeReviewActionResponse, error)
}

type creativeReviewServiceInterface struct {
	client *soap.Client
}

func NewCreativeReviewServiceInterface(client *soap.Client) CreativeReviewServiceInterface {
	return &creativeReviewServiceInterface{
		client: client,
	}
}

func (service *creativeReviewServiceInterface) GetCreativeReviewsByStatementContext(ctx context.Context, request *GetCreativeReviewsByStatement) (*GetCreativeReviewsByStatementResponse, error) {
	response := new(GetCreativeReviewsByStatementResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *creativeReviewServiceInterface) GetCreativeReviewsByStatement(request *GetCreativeReviewsByStatement) (*GetCreativeReviewsByStatementResponse, error) {
	return service.GetCreativeReviewsByStatementContext(
		context.Background(),
		request,
	)
}

func (service *creativeReviewServiceInterface) PerformCreativeReviewActionContext(ctx context.Context, request *PerformCreativeReviewAction) (*PerformCreativeReviewActionResponse, error) {
	response := new(PerformCreativeReviewActionResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *creativeReviewServiceInterface) PerformCreativeReviewAction(request *PerformCreativeReviewAction) (*PerformCreativeReviewActionResponse, error) {
	return service.PerformCreativeReviewActionContext(
		context.Background(),
		request,
	)
}
